trigger:
- main  # Define the branch to trigger the pipeline

resources:
- repo: self
variables:
  dockerRegistryServiceConnection: 'Docker ACR'
  imageRepository: 'atari/kt103-goapp'
  containerRegistry: 'Docker ACR'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'